# Generated by Django 5.0.3 on 2024-04-02 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Shahar')),
            ],
        ),
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Yo'nalish")),
                ('image', models.ImageField(upload_to='img/', verbose_name='rasm')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Vakansiya')),
                ('company_name', models.CharField(max_length=100, verbose_name='Kompaniya nomi')),
                ('required_work_experience', models.CharField(max_length=100, verbose_name='Ish tajriba')),
                ('requirements', models.TextField(verbose_name='Talablar')),
                ('salary', models.IntegerField(verbose_name='Maosh')),
                ('image', models.ImageField(upload_to='img/', verbose_name='Rasm')),
                ('addres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area', verbose_name='Manzil')),
                ('yonalish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.yonalish', verbose_name="Yo'nalish")),
            ],
        ),
    ]
